#!/bin/sh

if [[ $1 == install ]]; then

echo "Backing up original hosts file"
mkdir /etc/BackupHosts
cp -a /etc/hosts /etc/BackupHosts/originalhosts
exit 0

fi

if [[ $1 == upgrade && $2 == 1.2 || $1 == upgrade && $2 == 1.1 ]]; then

echo "Upgrade from 1.2/1.1 detected. Creating Backup from Stock."
mkdir /etc/BackupHosts
cp -a /etc/MinimalHostsBlocker/hostsstock /etc/BackupHosts/originalhosts
exit 0

fi
